FROM ubuntu:16.04

#LABEL Efa-GmbH <team@efa-gmbh.com>
LABEL https://github.com/nswarnkar/janus_docker
LABEL com.example.vendor="ACME Incorporated"
LABEL com.example.label-with-value="foo"
LABEL version="1.0"

RUN sed -i 's/archive.ubuntu.com/mirror.aarnet.edu.au\/pub\/ubuntu\/archive/g' /etc/apt/sources.list

# Copy installation scripts in
COPY *.sh ./

# Prepare the system
RUN ./install_depends.sh

## Install libsrtp 2.0.0
#RUN ./libsrtp.sh
#
## Install usrsctp for data channel support
#RUN ./usrsctp.sh
#
## Install rabbitmq
#RUN ./rabbitmq.sh
#
## Install websocket dependencies
#RUN ./websockets.sh
#
## Compile & install Janus
#RUN ./install_janus.sh
#
## Put configs in place
#COPY conf/*.cfg /opt/janus/etc/janus/
#
## Declare the ports we use
#EXPOSE 80 7088 8088 8188 5672 25672
#
## Define the default start-up command
#CMD ./startup.sh
